import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '../Components/navigation'
import "bootstrap/dist/css/bootstrap.min.css"
import SessionProviderAuth from '../context/SessionProviderAuth'
import ContexCart from '@/context/contexCart'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, showNavigation }) {
  return (
    <html lang="en">
      <body>
        <SessionProviderAuth>
          <ContexCart>
            { showNavigation && <Navigation/>}
            {/* <Navigation /> */}
            {children}
          </ContexCart>
        </SessionProviderAuth>

      </body>
    </html>
  )
}
